# Generated by Django 4.2.2 on 2023-06-11 23:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("brainservice", "0003_alter_profile_email"),
    ]

    operations = [
        migrations.AddField(
            model_name="channel",
            name="team",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="brainservice.team",
            ),
        ),
    ]
