# Generated by Django 4.2.2 on 2023-06-12 08:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import markdownx.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("brainservice", "0004_channel_team"),
    ]

    operations = [
        migrations.AlterField(
            model_name="channel",
            name="team",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="brainservice.team",
            ),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name="Post",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=50)),
                ("content", models.TextField()),
                (
                    "docs_content",
                    markdownx.models.MarkdownxField(blank=True, null=True),
                ),
                (
                    "arg_type",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("AGREE", "Agree"),
                            ("NETURAL", "Netural"),
                            ("DISAGREE", "Disagree"),
                        ],
                        max_length=50,
                        null=True,
                    ),
                ),
                ("arg_tree_level", models.IntegerField(blank=True, null=True)),
                (
                    "image",
                    models.ImageField(
                        blank=True, upload_to="brainservice/images/%Y/%m/%d/"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "arg_tree_parent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="arg_tree_children",
                        to="brainservice.post",
                    ),
                ),
                (
                    "channel",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="brainservice.channel",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
