# Generated by Django 4.2.2 on 2023-06-12 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("brainservice", "0006_alter_post_arg_tree_parent_alter_post_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="content",
            field=models.TextField(blank=True, null=True),
        ),
    ]
